export function getElements() {
    return {
        form: document.getElementById("newsletter-form"),
        scheduleTypeSelect: document.getElementById("schedule-type"),
        specificDateTimeSection: document.getElementById("specific-datetime"),
        customRecurringSection: document.getElementById("custom-recurring"),
        weekdayButtons: document.querySelectorAll(".weekday-btn"),
        submitBtn: document.getElementById("submit-btn"),
        messageContainer: document.getElementById("message-container"),

        loginContainer: document.getElementById("login-container"),
        appContainer: document.getElementById("app-container"),
        loginBtn: document.getElementById("login-btn"),
        logoutBtn: document.getElementById("logout-btn"),
        userInfo: document.getElementById("user-info"),
        userEmail: document.getElementById("user-email"),
        plansLoginBtn: document.getElementById("plans-login-btn"),
        profileBtn: document.getElementById("profile-btn"),
        profileMenu: document.getElementById("profile-menu"),
        progressPercent: document.getElementById("progress-percent"),
        progressStatus: document.getElementById("progress-status"),
        progressCard: document.getElementById("progress-card"),
        progressBar: document.getElementById("progress-bar"),
        progressCheck: document.getElementById("progress-check"),
        successModal: document.getElementById("success-modal"),
        successModalCard: document.getElementById("success-modal-card"),
        successModalClose: document.getElementById("success-modal-close"),
        successModalDone: document.getElementById("success-modal-done"),
        successModalMessage: document.getElementById("success-modal-message"),
        successModalIds: document.getElementById("success-modal-ids"),
    };
}
